package com.menyi.aio.bean;

/**
 * ViewRefPayId generated by MyEclipse Persistence Tools
 */

public class ViewRefPay implements java.io.Serializable {

	// Fields

	private String id;

	private String billNo;

	private Double totalTaxAmount;

	private Double alreadyPayAmt;

	private Double backAmount;

	private Double needPayAmt;

	private String buyOrderNo;

	private String buyOrderId;

	private String comFullName;

	private String empFullName;

	private String deptFullName;

	private String companyCode;

	private String employeeId;

	private String departmentCode;

	private String billType;

	private String billName;

	private String scompanyId;

	private String billDate;

	// Constructors

	/** default constructor */
	public ViewRefPay() {
	}

	/** minimal constructor */
	public ViewRefPay(String id, String billNo, String billType,
			String billDate) {
		this.id = id;
		this.billNo = billNo;
		this.billType = billType;
		this.billDate = billDate;
	}

	

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public Double getTotalTaxAmount() {
		return this.totalTaxAmount;
	}

	public void setTotalTaxAmount(Double totalTaxAmount) {
		this.totalTaxAmount = totalTaxAmount;
	}

	public Double getAlreadyPayAmt() {
		return this.alreadyPayAmt;
	}

	public void setAlreadyPayAmt(Double alreadyPayAmt) {
		this.alreadyPayAmt = alreadyPayAmt;
	}

	public Double getBackAmount() {
		return this.backAmount;
	}

	public void setBackAmount(Double backAmount) {
		this.backAmount = backAmount;
	}

	public Double getNeedPayAmt() {
		return this.needPayAmt;
	}

	public void setNeedPayAmt(Double needPayAmt) {
		this.needPayAmt = needPayAmt;
	}

	public String getBuyOrderNo() {
		return this.buyOrderNo;
	}

	public void setBuyOrderNo(String buyOrderNo) {
		this.buyOrderNo = buyOrderNo==null?"":buyOrderNo;
	}

	public String getBuyOrderId() {
		return this.buyOrderId;
	}

	public void setBuyOrderId(String buyOrderId) {
		this.buyOrderId = buyOrderId==null?"":buyOrderId;
	}

	public String getComFullName() {
		return this.comFullName;
	}

	public void setComFullName(String comFullName) {
		this.comFullName = comFullName;
	}

	public String getEmpFullName() {
		return this.empFullName;
	}

	public void setEmpFullName(String empFullName) {
		this.empFullName = empFullName;
	}

	public String getDeptFullName() {
		return this.deptFullName;
	}

	public void setDeptFullName(String deptFullName) {
		this.deptFullName = deptFullName;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getBillType() {
		return this.billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	public String getBillName() {
		return this.billName;
	}

	public void setBillName(String billName) {
		this.billName = billName;
	}

	public String getScompanyId() {
		return this.scompanyId;
	}

	public void setScompanyId(String scompanyId) {
		this.scompanyId = scompanyId;
	}

	public String getBillDate() {
		return this.billDate;
	}

	public void setBillDate(String billDate) {
		this.billDate = billDate;
	}


}