package com.menyi.aio.bean;

/**
 * ViewRefReceiveId generated by MyEclipse Persistence Tools
 */

public class ViewRefReceive implements java.io.Serializable {

	// Fields

	private String id;

	private String billNo;

	private Double totalTaxAmount;

	private Double totalAlrAccAmt;

	private Double backAmount;

	private Double needReturnAmt;

	private String salesOrderNo;

	private String salesOrderId;

	private String comFullName;

	private String empfullname;

	private String deptfullname;

	private String companycode;

	private String employeeId;

	private String departmentCode;

	private String billType;

	private String billName;

	private String scompanyId;





	
	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo==null?"":billNo;
	}

	public Double getTotalTaxAmount() {
		return this.totalTaxAmount;
	}

	public void setTotalTaxAmount(Double totalTaxAmount) {
		this.totalTaxAmount = totalTaxAmount;
	}

	public Double getTotalAlrAccAmt() {
		return this.totalAlrAccAmt;
	}

	public void setTotalAlrAccAmt(Double totalAlrAccAmt) {
		this.totalAlrAccAmt = totalAlrAccAmt;
	}

	public Double getBackAmount() {
		return this.backAmount;
	}

	public void setBackAmount(Double backAmount) {
		this.backAmount = backAmount;
	}

	public Double getNeedReturnAmt() {
		return this.needReturnAmt;
	}

	public void setNeedReturnAmt(Double needReturnAmt) {
		this.needReturnAmt = needReturnAmt;
	}

	public String getSalesOrderNo() {
		return this.salesOrderNo;
	}

	public void setSalesOrderNo(String salesOrderNo) {
		this.salesOrderNo = salesOrderNo==null?"":salesOrderNo;
	}

	public String getSalesOrderId() {
		return this.salesOrderId;
	}

	public void setSalesOrderId(String salesOrderId) {
		this.salesOrderId = salesOrderId==null?"":salesOrderId;;
	}

	public String getComFullName() {
		return this.comFullName;
	}

	public void setComFullName(String comFullName) {
		this.comFullName = comFullName;
	}

	public String getEmpfullname() {
		return this.empfullname;
	}

	public void setEmpfullname(String empfullname) {
		this.empfullname = empfullname;
	}

	public String getDeptfullname() {
		return this.deptfullname;
	}

	public void setDeptfullname(String deptfullname) {
		this.deptfullname = deptfullname;
	}

	public String getCompanycode() {
		return this.companycode;
	}

	public void setCompanycode(String companycode) {
		this.companycode = companycode;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getDepartmentCode() {
		return this.departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getBillType() {
		return this.billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	public String getBillName() {
		return this.billName;
	}

	public void setBillName(String billName) {
		this.billName = billName;
	}

	public String getScompanyId() {
		return this.scompanyId;
	}

	public void setScompanyId(String scompanyId) {
		this.scompanyId = scompanyId;
	}

	

}